[package]
name = "runner-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = { version = "1.0.141", features = ["c++17"] }
middle-rs = { path = "../middle-rs" }

[build-dependencies]
cmake = "0.1.54"
cxx-build = { version = "1.0.141", features = ["parallel"] }
